config/routes.rb
Rails.application.routes.draw do
  resources :sendmails

end

app/models/sendmail.rb
#!/usr/bin/env ruby
class Sendmail
  attr_reader :to
  attr_writer :to
  attr_reader :subject
  attr_writer :subject
  attr_reader :body
  attr_writer :body
  attr_reader :response
  attr_writer :response

  
  def initialize(to, subject, body, response)
   @to = to
   @subject = subject
   @body = body
   @response = response
  end
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/sendmails_controller.rb
require 'rubygems'
require 'json'
require 'net/http'

class SendmailsController < ApplicationController
#  before_action :set_sendmail,only: [:show, :edit, :update, :destroy]


  # GET /sendmails
  # GET /sendmails.json
  def index
    @sendmails = Sendmail.all
  end



  # POST /sendmails
  # POST /sendmails.json
  def create
    
      txtresponse = ''
      to = params[:to]
      subject = params[:subject]
      body = params[:body]
      
          if to.to_s == ''
	  	txtresponse=  '"to" field missing'
	  end	
          if subject.to_s == ''
	  	txtresponse=  txtresponse + ' "subject" field missing'
	  end	
	  if body.to_s == ''
	  	txtresponse=  txtresponse + ' "body" field missing'
          end
          if txtresponse == ''
             txtresponse = 'Success'
          end
          
          @sendmail = Sendmail.new(to, subject, body, txtresponse) 
	  
	  if txtresponse == 'Success'
            UserMailer.send_email(to, subject, body ).deliver
            puts 'Mail Sent'
            respond_to do |format|  
              format.json { render :show, status => 200 }
            end
          else
            puts txtresponse
            respond_to do |format|  
              format.json { render :show, status: :bad_request}
            end
          end	  
  end


  private
=begin  
    # Use callbacks to share common setup or constraints between actions.
    def set_sendmail
      @sendmail = Sendmail.find(params[:id])
    end
=end
    # Never trust parameters from the scary internet, only allow the white list through.
    def sendmail_params
      params.require(:sendmail).permit(:to, :subject, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sendmails_helper.rb
module SendmailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sendmails/_form.html.erb
<%= form_for(@sendmail) do |f| %>
  <% if @sendmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sendmail.errors.count, "error") %> prohibited this sendmail from being saved:</h2>

      <ul>
      <% @sendmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sendmails/edit.html.erb
<h1>Editing sendmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @sendmail %> |
<%= link_to 'Back', sendmails_path %>

app/views/sendmails/index.html.erb
<h1>Listing sendmails</h1>

<table>
  <thead>
    <tr>
      <th>To</th>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sendmails.each do |sendmail| %>
      <tr>
        <td><%= sendmail.to %></td>
        <td><%= sendmail.subject %></td>
        <td><%= sendmail.body %></td>
        <td><%= link_to 'Show', sendmail %></td>
        <td><%= link_to 'Edit', edit_sendmail_path(sendmail) %></td>
        <td><%= link_to 'Destroy', sendmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sendmail', new_sendmail_path %>

app/views/sendmails/new.html.erb
<h1>New sendmail</h1>

<%= render 'form' %>

<%= link_to 'Back', sendmails_path %>

app/views/sendmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @sendmail.to %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @sendmail.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @sendmail.body %>
</p>

<%= link_to 'Edit', edit_sendmail_path(@sendmail) %> |
<%= link_to 'Back', sendmails_path %>